name: my-rails
description: Example component that includes a Rails application with a postgres backend
homepage: https://github.com/architect-templates/ruby-on-rails

services:
  # Name of the Rails service
  rails:
    # Build context is the location of your application relative to the architect.yml file
    build:
      context: .
    # Set environment variables for your application here
    environment:
      INGRESS_HOST: ${{ ingresses.main.host }}
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1 # Consider disabling for production
    # Main interface port used to help define the url in the top level `interfaces` block
    interfaces:
      main:
        port: 3000
    # Debug block is used to enable hot-reloading to make real-time changes to an
    #   application while running `architect dev`. For more info, see -
    #   https://docs.architect.io/components/local-configuration/#hot-reloading
    debug:
      environment:
        RAILS_ENV: development
      volumes:
        app:
          # Path to source code relative to the architect.yml file
          host_path: .
          # The `WORKDIR` defined in the Dockerfile
          mount_path: /myapp
        gem-cache:
          mount_path: /usr/local/bundle/gems
        node-modules:
          mount_path: /myapp/node_modules

# interfaces are used to expose our application to the gateway, allowing
#   other services and dependencies to connect to one another.
#   For more info - https://docs.architect.io/components/interfaces/
interfaces:
  # Interface for our main Rails application
  main:
    url: ${{ services.rails.interfaces.main.url }}
    ingress:
      subdomain: app
