name: ruby-on-rails

description: |
  An example Architect component that uses Ruby-on-Rails serving a full-stack
  web application.

keywords:
  - ruby-on-rails

# Below are the configured services for the Ruby-on-Rails component.
# For more info - https://docs.architect.io/components/services/
services:
  ### This service is the actual Ruby-on-Rails component ###
  rails:
    # Build context is the location of your application relative to the architect.yml file
    build:
      context: .
    # Set environment variables for your application here
    environment:
      INGRESS_HOST: ${{ ingresses.main.host }}
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1 # Consider disabling for production
    # The liveness_probe makes sure the application is healthy - if not, it will re-start the application
    liveness_probe:
      command: curl --fail 0.0.0.0:3000
      initial_delay: 5s
      interval: 5s
      failure_threshold: 2
    # Main interface port used to help define the url in the top level `interfaces` block at the bottom of this file
    interfaces:
      main:
        port: 3000
    # Debug block is used to modify behavior when running `architect dev` (without the --debug=false flag)
    #   One common example is to enable hot-reloading for local development. For more info, see -
    #   https://docs.architect.io/components/local-configuration/#hot-reloading
    debug:
      environment:
        RAILS_ENV: development
      volumes:
        # Volume for the application
        app:
          # Path to source code we want to mount relative to the architect.yml file
          host_path: .
          # The `WORKDIR` defined in the Dockerfile, where we want our code to be mounted
          mount_path: /myapp
        gem-cache:
          mount_path: /usr/local/bundle/gems
        node-modules:
          mount_path: /myapp/node_modules

# interfaces are used to expose our application to the gateway, allowing
#   other services and dependencies to connect to one another.
#   For more info - https://docs.architect.io/components/interfaces/
interfaces:
  # Interface for our main Ruby-on-Rails application
  main:
    url: ${{ services.rails.interfaces.main.url }}
    ingress:
      subdomain: app
