name: my-rails

services:
  rails:
    build:
      context: .
    environment:
      INGRESS_HOST: ${{ ingresses.main.host }}
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1 # Consider disabling for production
    interfaces:
      main:
        port: 3000
    debug:
      environment:
        RAILS_ENV: development
      volumes:
        app:
          host_path: .
          mount_path: /myapp
        gem-cache:
          mount_path: /usr/local/bundle/gems
        node-modules:
          mount_path: /myapp/node_modules

interfaces:
  main:
    url: ${{ services.rails.interfaces.main.url }}
    ingress:
      subdomain: app
